// @generated by protobuf-ts 2.8.2 with parameter use_proto_field_name,generate_dependencies
// @generated from protobuf file "qroma-types.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message Qroma_LogMessage
 */
export interface Qroma_LogMessage {
    /**
     * @generated from protobuf field: uint32 tick = 1;
     */
    tick: number;
    /**
     * @generated from protobuf field: string message = 2;
     */
    message: string;
}
/**
 * @generated from protobuf message FileData
 */
export interface FileData {
    /**
     * @generated from protobuf field: string filename = 1;
     */
    filename: string;
    /**
     * @generated from protobuf field: uint32 filesize = 2;
     */
    filesize: number;
    /**
     * @generated from protobuf field: uint32 checksum = 3;
     */
    checksum: number;
}
/**
 * @generated from protobuf message FirmwareDetails
 */
export interface FirmwareDetails {
    /**
     * @generated from protobuf field: string buildTime = 1;
     */
    buildTime: string;
    /**
     * @generated from protobuf field: string qromaFirmwareLibVersion = 2;
     */
    qromaFirmwareLibVersion: string;
    /**
     * @generated from protobuf field: string qromaDeviceFirmwareVersion = 3;
     */
    qromaDeviceFirmwareVersion: string;
}
/**
 * @generated from protobuf message HeartbeatResponse
 */
export interface HeartbeatResponse {
    /**
     * @generated from protobuf field: uint32 uptimeInMs = 1;
     */
    uptimeInMs: number;
    /**
     * @generated from protobuf field: uint32 heartbeatTicks = 2;
     */
    heartbeatTicks: number;
}
/**
 * @generated from protobuf enum Qroma_LogLevel
 */
export enum Qroma_LogLevel {
    /**
     * @generated from protobuf enum value: LogLevel_All = 0;
     */
    LogLevel_All = 0,
    /**
     * @generated from protobuf enum value: LogLevel_Info = 10;
     */
    LogLevel_Info = 10,
    /**
     * @generated from protobuf enum value: LogLevel_Error = 100;
     */
    LogLevel_Error = 100,
    /**
     * @generated from protobuf enum value: LogLevel_Nothing = 255;
     */
    LogLevel_Nothing = 255
}
/**
 * @generated from protobuf enum Qroma_DebugCommMode
 */
export enum Qroma_DebugCommMode {
    /**
     * @generated from protobuf enum value: DebugCommMode_NotSet = 0;
     */
    DebugCommMode_NotSet = 0,
    /**
     * @generated from protobuf enum value: DebugCommMode_None = 1;
     */
    DebugCommMode_None = 1,
    /**
     * @generated from protobuf enum value: DebugCommMode_SerialOnly = 2;
     */
    DebugCommMode_SerialOnly = 2,
    /**
     * @generated from protobuf enum value: DebugCommMode_BluetoothOnly = 3;
     */
    DebugCommMode_BluetoothOnly = 3,
    /**
     * @generated from protobuf enum value: DebugCommMode_SerialAndBluetooth = 4;
     */
    DebugCommMode_SerialAndBluetooth = 4
}
/**
 * @generated from protobuf enum GetFileStatusCode
 */
export enum GetFileStatusCode {
    /**
     * @generated from protobuf enum value: GFSC_NOT_SET = 0;
     */
    GFSC_NOT_SET = 0,
    /**
     * @generated from protobuf enum value: GFSC_FILE_EXISTS = 1;
     */
    GFSC_FILE_EXISTS = 1,
    /**
     * @generated from protobuf enum value: GFSC_ERR_OPEN_FILE = 2;
     */
    GFSC_ERR_OPEN_FILE = 2,
    /**
     * @generated from protobuf enum value: GFSC_ERR_INVALID_FILE_PATH = 3;
     */
    GFSC_ERR_INVALID_FILE_PATH = 3
}
/**
 * @generated from protobuf enum HeartbeatType
 */
export enum HeartbeatType {
    /**
     * @generated from protobuf enum value: HeartbeatType_NotSet = 0;
     */
    HeartbeatType_NotSet = 0,
    /**
     * @generated from protobuf enum value: HeartbeatType_None = 1;
     */
    HeartbeatType_None = 1,
    /**
     * @generated from protobuf enum value: HeartbeatType_Interval = 2;
     */
    HeartbeatType_Interval = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class Qroma_LogMessage$Type extends MessageType<Qroma_LogMessage> {
    constructor() {
        super("Qroma_LogMessage", [
            { no: 1, name: "tick", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Qroma_LogMessage>): Qroma_LogMessage {
        const message = { tick: 0, message: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Qroma_LogMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Qroma_LogMessage): Qroma_LogMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 tick */ 1:
                    message.tick = reader.uint32();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Qroma_LogMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 tick = 1; */
        if (message.tick !== 0)
            writer.tag(1, WireType.Varint).uint32(message.tick);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Qroma_LogMessage
 */
export const Qroma_LogMessage = new Qroma_LogMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FileData$Type extends MessageType<FileData> {
    constructor() {
        super("FileData", [
            { no: 1, name: "filename", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "filesize", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "checksum", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<FileData>): FileData {
        const message = { filename: "", filesize: 0, checksum: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<FileData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FileData): FileData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string filename */ 1:
                    message.filename = reader.string();
                    break;
                case /* uint32 filesize */ 2:
                    message.filesize = reader.uint32();
                    break;
                case /* uint32 checksum */ 3:
                    message.checksum = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: FileData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string filename = 1; */
        if (message.filename !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.filename);
        /* uint32 filesize = 2; */
        if (message.filesize !== 0)
            writer.tag(2, WireType.Varint).uint32(message.filesize);
        /* uint32 checksum = 3; */
        if (message.checksum !== 0)
            writer.tag(3, WireType.Varint).uint32(message.checksum);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message FileData
 */
export const FileData = new FileData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FirmwareDetails$Type extends MessageType<FirmwareDetails> {
    constructor() {
        super("FirmwareDetails", [
            { no: 1, name: "buildTime", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "qromaFirmwareLibVersion", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "qromaDeviceFirmwareVersion", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<FirmwareDetails>): FirmwareDetails {
        const message = { buildTime: "", qromaFirmwareLibVersion: "", qromaDeviceFirmwareVersion: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<FirmwareDetails>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FirmwareDetails): FirmwareDetails {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string buildTime */ 1:
                    message.buildTime = reader.string();
                    break;
                case /* string qromaFirmwareLibVersion */ 2:
                    message.qromaFirmwareLibVersion = reader.string();
                    break;
                case /* string qromaDeviceFirmwareVersion */ 3:
                    message.qromaDeviceFirmwareVersion = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: FirmwareDetails, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string buildTime = 1; */
        if (message.buildTime !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.buildTime);
        /* string qromaFirmwareLibVersion = 2; */
        if (message.qromaFirmwareLibVersion !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.qromaFirmwareLibVersion);
        /* string qromaDeviceFirmwareVersion = 3; */
        if (message.qromaDeviceFirmwareVersion !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.qromaDeviceFirmwareVersion);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message FirmwareDetails
 */
export const FirmwareDetails = new FirmwareDetails$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HeartbeatResponse$Type extends MessageType<HeartbeatResponse> {
    constructor() {
        super("HeartbeatResponse", [
            { no: 1, name: "uptimeInMs", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "heartbeatTicks", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<HeartbeatResponse>): HeartbeatResponse {
        const message = { uptimeInMs: 0, heartbeatTicks: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<HeartbeatResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HeartbeatResponse): HeartbeatResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 uptimeInMs */ 1:
                    message.uptimeInMs = reader.uint32();
                    break;
                case /* uint32 heartbeatTicks */ 2:
                    message.heartbeatTicks = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HeartbeatResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 uptimeInMs = 1; */
        if (message.uptimeInMs !== 0)
            writer.tag(1, WireType.Varint).uint32(message.uptimeInMs);
        /* uint32 heartbeatTicks = 2; */
        if (message.heartbeatTicks !== 0)
            writer.tag(2, WireType.Varint).uint32(message.heartbeatTicks);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message HeartbeatResponse
 */
export const HeartbeatResponse = new HeartbeatResponse$Type();
